language: cpp
dist: trusty

addons:
    apt:
        sources:
            - llvm-toolchain-trusty-6.0
        packages:
            - clang-6.0

before_script:
    - clang++-6.0 --version

script:
    - clang++-6.0 -Wunreachable-code -Werror test.cpp test_fun.cpp -o test && ./test
