language: cpp
dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
        packages:
            - clang-6.0
            - libstdc++-8-dev
            - libboost-all-dev

before_script:
    - clang++-6.0 --version

script:
    - clang++-6.0 -Wall -Wextra -Werror -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-newline-eof -Wno-padded -Wno-sign-conversion -Wno-exit-time-destructors -Wno-global-constructors -Wno-weak-vtables -Wno-c99-extensions -Wno-shorten-64-to-32 -Wno-range-loop-analysis -Wno-switch-enum -Wno-old-style-cast -Wodr -Wshadow -Wredundant-decls -Wcast-align -Wmissing-declarations -Wmissing-include-dirs -Wredundant-decls -Wformat=2 -Wmissing-format-attribute -Wformat-nonliteral -Warray-bounds -Wimplicit-fallthrough -Wduplicate-enum -Wold-style-cast -Wformat=2 -Wno-unused-parameter -Wno-missing-braces -Wno-unused-command-line-argument -fsanitize=undefined -ggdb -O0 -std=c++17 test_notification_server.cpp -c -o test_notification_server.o
